## Introduction to NumPy

In [1]:
# Import Libraries
import numpy as np

In [2]:
# Creating a Python List
python_list = [1, 2 ,3 ,4 ,5]

In [3]:
# Converting Python list to numpy array
numpy_array1 = np.array(python_list)

In [4]:
numpy_array1

array([1, 2, 3, 4, 5])

In [5]:
# Create two python list say 'lisy_x' and 'list_y'
list_x = list(range(100000))
list_y = list(range(100000))

In [6]:
# Create two numpy array (say 'arr_x' and 'arr_y') using the above two list
arr_x = np.array(list_x)
arr_y = np.array(list_y)

In [7]:
# Define a function to calculate sum using python lists (list_x, list_y)
def list_sum():
    z = [] # a empty list to store sum
    for i in range(len(list_x)):
        z.append(list_x[i]+list_y[i])

In [8]:
# Define a function to calculate sum using numpy array (arr_x, arr_y)
def numpy_arr_sum():
    # In numpy we can directly perform sum element-wise as 
    z = arr_x + arr_y 

In [9]:
# Import timer class from timeit library
from timeit import Timer

In [10]:
timer_obj1 = Timer("list_sum()", "from __main__ import list_sum")
timer_obj2 = Timer("numpy_arr_sum()", "from __main__ import numpy_arr_sum")

print("Pure Python version:", timer_obj1.timeit(1000))
print("NumPy Version:",timer_obj2.timeit(1000))

Pure Python version: 15.558741734000023
NumPy Version: 0.04981063200011704


Notice the time taken by both th functions (i.e list_sum() and numpy_arr_sum()) to perform the same task.

In [11]:
# Creating a numpy array using the nested list
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Checking the size of the numpya array
arr.size

9

In [13]:
# Checking the type of data present in numpy array
arr.dtype

dtype('int64')

In [14]:
# Checking the datatype of the array
type(arr)

numpy.ndarray

In [15]:
# Checking the shape of the numpy array
arr.shape

(3, 3)

In [16]:
# Checking the dimensions of the numpy array
arr.ndim

2

In [17]:
# Checking the type of object - 
type(python_list)

list

In [18]:
# 'dtype' method is not supported on the Python Lists
python_list.dtype

AttributeError: 'list' object has no attribute 'dtype'

Some basic array functions 

- linspace()
- arange()
- zeros()
- ones()

In [19]:
# Using the linspace function without num - Number of samples to generate
arr_a = np.linspace(start=5, stop=25)
arr_a

array([ 5.        ,  5.40816327,  5.81632653,  6.2244898 ,  6.63265306,
        7.04081633,  7.44897959,  7.85714286,  8.26530612,  8.67346939,
        9.08163265,  9.48979592,  9.89795918, 10.30612245, 10.71428571,
       11.12244898, 11.53061224, 11.93877551, 12.34693878, 12.75510204,
       13.16326531, 13.57142857, 13.97959184, 14.3877551 , 14.79591837,
       15.20408163, 15.6122449 , 16.02040816, 16.42857143, 16.83673469,
       17.24489796, 17.65306122, 18.06122449, 18.46938776, 18.87755102,
       19.28571429, 19.69387755, 20.10204082, 20.51020408, 20.91836735,
       21.32653061, 21.73469388, 22.14285714, 22.55102041, 22.95918367,
       23.36734694, 23.7755102 , 24.18367347, 24.59183673, 25.        ])

In [20]:
# Using the linspace function with num - Number of samples to generate
arr_a = np.linspace(start=17, stop=31,num=50)
arr_a

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [21]:
# Use of the arange function
arr_b = np.arange(10)
arr_b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Use of the zeros function
arr_c = np.zeros(20)
arr_c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [23]:
# Use of the ones functions
arr_d = np.ones(10)
arr_d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
# Adding and elements in the array
np.append(arr,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 15])

In [25]:
# We can also use python list to append an element
l = [5, 10, 15, 20, 25]
arr = np.append(l, 10)
arr

array([ 5, 10, 15, 20, 25, 10])

In [26]:
type(arr)

numpy.ndarray

In [27]:
# Note: NumPy arry doesn't support append directly on the array
arr.append(10)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [28]:
# Removing an element at particlar index
np.delete(arr, 2)

array([ 5, 10, 20, 25, 10])

In [29]:
# Use sort method to sort an array
ar1 = [3, 1, 30, 45, 12, 10]
np.sort(ar1)

array([ 1,  3, 10, 12, 30, 45])

In [30]:
arr_3 = np.arange(24)
arr_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
# Reshaping in shape (8, 3)
np.reshape(arr_3, (8, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [32]:
# Reshaping in shape (8, 3)
np.reshape(arr_3, (6, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
np.reshape(arr_3, (2, 12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [34]:
# We can also reshape the python list but the resultant object will be the numpy array
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11]

reshaped_arr = np.reshape(l, (2,6))
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [35]:
type(reshaped_arr)

numpy.ndarray

In [36]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]
array = np.array(L)
c = np.sort(array)
d = np.delete(c, 5)
c

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [37]:
d

array([ 2,  3,  7,  8, 10, 13, 22, 23, 25, 41, 46, 54])

In [38]:
arr

array([ 5, 10, 15, 20, 25, 10])

In [39]:
arr[0:3:2]

array([ 5, 15])

In [40]:
ary = np.arange(25) 
np.reshape(ary, (5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])