<a href="https://colab.research.google.com/github/kunalburgul/MLDS_Learning/blob/master/Tensorflow/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **In this notebook, we are going to cover some of the most fundamental concepts of tensord using Tensorflow.**

Topics Covered: 

- Introduction to Tensors
- Getting information from tensors. 
- Manipulating tensors
- Tensors & Numpy
- Using @tf.function (a way to speedup your regular python function)
- Using GPUs with TensorFlow (or TPUs)
- Exercises to Practise.

## **Introduction to Tensors**

In [ ]:
# Import TensorFlow
import tensorflow as tf 
print(tf.__version__)

2.4.1


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Check a vector  
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of the vector
vector.ndim

1

In [ ]:
# Create a matric (a matrix has more than 1 dimension)
matrix = tf.constant([[6, 1],
                     [5, 8]]) 
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 1],
       [5, 8]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[61., 58.],
                              [11., 21.],
                              [56., 58.]], dtype=tf.float16) # specify  the data type with dtype parameter
another_matrix  

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[61., 58.],
       [11., 21.],
       [56., 58.]], dtype=float16)>

In [ ]:
# Let's check the number of the dimension using ndim
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [15, 16, 17]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [15, 16, 17]]], dtype=int32)>

In [ ]:
# Let's check the dimnetsions 
tensor.ndim

3

What all we have learnt so far

- **Scalar**: A single number
- **Vector**: A number with direction (e.g windspeed and direction)
- **Matrix**: A 2-dimensional array of numbers
- **Tensor**: An n-dimentsional array of numbers 
(where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

Creating the tensors with `tf.Varaible`

In [ ]:
# Creating the same tensor with the th.Varaible() as above
changable_tensor = tf.Variable([10, 7]) 
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Now let's try to change the element in out changable tensor 
changable_tensor[0] = 1 

TypeError: ignored

In [ ]:
# Let's try out the assign() function to change it 
cahngable_tensor[0].assign(1)

In [ ]:
# Now let's  try this on the unchangaable tensor
unchangable_tensor[0].assign(1)

***Note***: *Rarely in practice we will need to decide whether to use `tf.constant` OR `tf.Variable` to create tensors, as tensorflow does this for you. However, if in doubt, use `tf.consant` and change it later on if needed.* 

### **Creating a Random Tensors**
 
Random tensors are tensors of some arbitary size which contain random numbers. 

In [ ]:
# Create a two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility 
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

 ### **Shuffle the ordere of elements in a tensor**
 

In [ ]:
# Shuffle a tensor (valuable for when u want to shuffle ur data inherent order dosen't effects learning)
not_shuffeled = tf.constant([[1, 2],
                             [2 ,3],
                             [4, 5]])
not_shuffeled.ndim

# Shuffle a non-shuffled tensor
tf.random.shuffle(not_shuffeled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffeled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [2, 3],
       [1, 2]], dtype=int32)>

In [ ]:

tf.random.shuffle(not_shuffeled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 2],
       [2, 3]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffeled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
not_shuffeled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [4, 5]], dtype=int32)>

**Exercise:** Read through the TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and pracatise writing 5 random tensors and shuffle them. 

In [ ]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(5,2))
random_3

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284]], dtype=float32)>

In [ ]:
tf.random.shuffle(random_3)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [-0.7535805 , -0.57166284],
       [ 0.09988727, -0.50998646],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [ ]:
tf.random.shuffle(random_3, seed=21)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284],
       [ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(21) # global level random seed 
tf.random.shuffle(random_3, seed=21) # Operational level random seed

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284],
       [ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(21)
tf.random.shuffle(random_3)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(22)
tf.random.shuffle(random_3)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7535805 , -0.57166284],
       [ 0.09988727, -0.50998646]], dtype=float32)>

It look like tensorflow has some rules like : 
Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

2. If the graph-level seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the graph-level seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both graph-level and operation-level seeds explicitly.

3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.

4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

> Rule 4 - It looks like if we want our shuffled tensors to be in the same order, we have got to use the global level random seed as well as the operaitonal level random seed:




### **Other ways to make tensors**

In [ ]:
tf.ones([10, 7]) 

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros(shape=(10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### **Turn NumPy arrays into Tensors**

- The main difference beteween Numpya arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computating).


In [ ]:
# You can also turn numpy arrays in tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Create a NumPy array betweem 1 and 35
numpy_A

# X = tf.constant(some_matrix) # Capital for matric or tensor
# y = tf.constant(vector) # Non-Capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### **Getting the information from the tensors**

When dealing with the tensors we should be probably be aware of the following attributes:

> - **Shape** - The length (number of elements) of each of the dimensions of a tensor. -------- ***tensor.shape***

> - **Rank** - The number of tensor dimensions.A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n. -------- ***tensor.ndim***

> - **Axis or dimension** - A particular dimension of a tensor. -------- ***tensor[0], tensor[:1]...***

> - **Size** - The total number of items in the tensor. -------- ***tf.size(tensor)***

In [ ]:
# Createa a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2 * 3 * 4 * 5

120

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of the tensor:", rank_4_tensor.shape)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of the elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of the tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Total number of the elements in our tensor: 120


 ### **Indexing tensors**

 Tensors can be indexed just like the python lists.

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [ ]:
# Get the fist two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_list[:1]

[1]

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
 # Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
 # Create a rank 2 tensoe (2 dimensions)
 rank_2_tensor = tf.constant([[10, 7], 
                              [1, 2]])
 rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row of the rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2], dtype=int32)>

In [ ]:
# Adding in extra dimension to our rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [ ]:
 # Alternative to tf.newaxis
 tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 1,  2]]], dtype=int32)>

In [ ]:
 tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 1,  2]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

### **Manipulating the Tensors  (tensor operations)**

**Basic Operations**

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to the tensor using the addition operator
tensor = tf.constant([[1, 2], 
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Multiplication alos work for the tensors
tensor * 10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Substracation if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### **Matrix Multiplication with tensor**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules out tensors (or matrices) need to fulllfill if we're going to matrix multiply them

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
tensor, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python opereator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4], 
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply the tensor of the same shape
tf.matmul(X, Y)

InvalidArgumentError: ignored

In [ ]:
# Lets change the shape of Y 
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# Try to multipy X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Can do the same with the transposr 
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
- `tf.matmul()`
- `tf.tensordot()`

In [ ]:
# Perfom the dot product on the X and Y  (require X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matirx multiplication between X and y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the values of Yn reshape Y and transposed Y
print("Normal Y: ")
print(Y, '\n')

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2,3)), '\n')

print('Y transposed:')
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing the matrix multiplication on two tensors and one of the axes dosen't line up, we will transpose (rather than reshape) one of the tensors to statisfy the matrix multiplcation rules.

### **Changing the datatype of the tensor**

In [ ]:
# Create a new tensor with default dtype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([1, 10])
C.dtype

tf.int32

In [ ]:
# Change form float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
C, E

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 1., 10.], dtype=float32)>)

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1., 10.], dtype=float16)>

### **Aggregating tensors**

Aggregating tensors = condensing them multiple values down to a smaller amount of values.

In [ ]:
# Getting the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute value 
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of the aggregation: 

- Get the minimum
- Get the maximum
- Get the mean of a tensor
- Get the sum of the  tensor

In [ ]:
# Creating a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([84, 27, 87, 63, 78, 58, 39, 61, 63, 67,  8, 65, 10, 90,  3, 50, 57,
       15, 30, 55, 61, 25, 59, 38, 68, 13, 16, 79, 73, 49, 14, 74, 24, 90,
       26,  1, 61, 98, 16, 69, 95, 80, 97, 86, 21, 86, 35, 22, 73, 48])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Find the maximum 
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2607>

***Exercise:***With what we've just learned, find the variance and standarad deviation of our 'E' tensor using TensorFlow methods.

In [ ]:
# Find the variance of out tensor 
tf.reduce_variance(E)

AttributeError: ignored

In [ ]:
# To find the variance of our tensor, we need access to tensorflow_probablity
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=800>

In [ ]:
tf.math.reduce_std(E)

TypeError: ignored

In [ ]:
 # Find the standard Deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.286398>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=800.12036>

### **Finding the positional maximum and minimim**

In [ ]:
# Create a new tensor for finding positional minimum and maximum 
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional of maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of F 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality 
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using the positional minimum index 
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# Check for equality 
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### **Squeezing a Tensor (removing all the single dimensions)**

In [ ]:
# Create a tensor to get started 
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

 ### **One-hot Encoding Tensors**

 

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="I Love DL", off_value="I like ML ") # on-value - 1, off-value - 0

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I Love DL', b'I like ML ', b'I like ML ', b'I like ML '],
       [b'I like ML ', b'I Love DL', b'I like ML ', b'I like ML '],
       [b'I like ML ', b'I like ML ', b'I Love DL', b'I like ML '],
       [b'I like ML ', b'I like ML ', b'I like ML ', b'I Love DL']],
      dtype=object)>

### **Few Common Mathematical operations**

#### Squaring, log, square root

In [ ]:
# Create a new tensor
H =  tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square the tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the squareroot (will error, requires non-int type)
tf.sqrt(H)

InvalidArgumentError: ignored

In [ ]:
# Find the squareroot
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# Fing the log 
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### **Tensors and NumPy**

Tensorflow intercats beautifully with NumPy arrays.

***Note: *** *One of the main difference between a Tensorflow tensor and NumPy array is that Tensor can be run on a GPU or TPU (for fater numerical progressing)*

In [ ]:
 # create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Conveert a tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert a J to NumPy array 
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J =  tf.constant([3.])
J

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>

In [ ]:
# The default types of each are slightly differnet
numpy_J = tf.constant(np.array([3., 7.,10.]))
tensor_J = tf.constant([3., 7., 10.])

# check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### **Finding access to GPUs**

In [ ]:
tf.config.list_physical_devices()
# tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

***Note:*** *If we have access to cuda enabled GPU, tensorflow will automatically use it whenever possible.*

# **TensorFlow Fundamentals Exercises**

## 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
scalar_1 = tf.constant(61)
vector_1 = tf.constant([58, 61])
matrix_1 = tf.constant([[1,2],
                       [3,4]])

scalar_1, vector_1, matrix_1

(<tf.Tensor: shape=(), dtype=int32, numpy=61>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([58, 61], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

## 2. Find the shape, rank and size of the tensors you created in 1. 

In [ ]:
scalar_1.shape, vector_1.shape, matrix_1.shape

(TensorShape([]), TensorShape([2]), TensorShape([2, 2]))

In [ ]:
tf.rank(scalar_1), tf.rank(vector_1), tf.rank(matrix_1)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [ ]:
scalar_1.ndim, vector_1.ndim, matrix_1.ndim

(0, 1, 2)

In [ ]:
tf.size(scalar_1), tf.size(vector_1), tf.size(matrix_1)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

## 3. Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [ ]:
tf.random.set_seed(21)
tensor_r1 = tf.random.uniform(shape=[5,300], minval=0, maxval=1,seed=21)
tensor_r1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.09922791, 0.53223455, 0.52585924, ..., 0.4796611 , 0.4639269 ,
        0.4557798 ],
       [0.88506544, 0.31801093, 0.46373725, ..., 0.72223055, 0.3143344 ,
        0.10065651],
       [0.43792868, 0.53827095, 0.9233161 , ..., 0.6988317 , 0.4151187 ,
        0.32154536],
       [0.9720415 , 0.27956104, 0.54739094, ..., 0.9366491 , 0.81880116,
        0.887401  ],
       [0.16646612, 0.29927325, 0.13273835, ..., 0.15087128, 0.59476304,
        0.04274666]], dtype=float32)>

In [ ]:
tf.random.set_seed(42)
tensor_r2 = tf.random.uniform(shape=[5,300], minval=0, maxval=1,seed=42)
tensor_r2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.4163028 , 0.26858163, 0.47968316, ..., 0.9737669 , 0.9777365 ,
        0.21718514],
       [0.9787899 , 0.9768691 , 0.6782458 , ..., 0.8427533 , 0.8693787 ,
        0.6705674 ],
       [0.6826352 , 0.06621385, 0.58875644, ..., 0.7543584 , 0.38940334,
        0.7927996 ],
       [0.11849666, 0.60407066, 0.34777546, ..., 0.605     , 0.9107114 ,
        0.50104   ],
       [0.72606504, 0.7984501 , 0.9777988 , ..., 0.5601653 , 0.27684855,
        0.19102657]], dtype=float32)>

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tensor_rm = tf.matmul(tensor_r1, tf.transpose(tensor_r2))
tensor_rm

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.50119 , 77.16258 , 76.36403 , 74.82988 , 80.28593 ],
       [80.98927 , 76.76718 , 78.65062 , 77.1055  , 84.75966 ],
       [78.20811 , 73.41794 , 76.75777 , 75.13246 , 77.59798 ],
       [77.4931  , 76.30494 , 74.63791 , 70.39154 , 79.016174],
       [79.565125, 79.22279 , 78.37762 , 75.78941 , 82.40608 ]],
      dtype=float32)>

## 5. Multiply the two tensors you created in 3 using dot product.


In [ ]:
tensor_rdp = tf.tensordot(tf.transpose(tensor_r1), tensor_r2, axes=1)
tensor_rdp

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.4425964 , 1.6403375 , 1.4065458 , ..., 1.8542055 , 1.9683418 ,
        1.4810677 ],
       [1.1506982 , 0.89707386, 1.1777575 , ..., 1.5291033 , 1.3439144 ,
        0.95282257],
       [1.4643468 , 1.0920308 , 1.4305425 , ..., 2.0049186 , 1.8121209 ,
        1.4568018 ],
       ...,
       [1.6041756 , 1.5668906 , 1.6046422 , ..., 2.2540956 , 2.263787  ,
        1.640632  ],
       [1.3130379 , 1.4286548 , 1.5464553 , ..., 1.8583516 , 1.7988733 ,
        1.164514  ],
       [0.643953  , 0.812217  , 0.8266256 , ..., 1.3320352 , 1.4783525 ,
        0.87419575]], dtype=float32)>

## 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [ ]:
tf.random.set_seed(10)
tensor_r3 = tf.random.uniform(shape=[224, 224,3], minval=0, maxval=1,seed=10)
tensor_r3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.9574727 , 0.8584739 , 0.6193379 ],
        [0.2191757 , 0.31577528, 0.7001637 ],
        [0.1357553 , 0.90233886, 0.57843506],
        ...,
        [0.6916183 , 0.18287396, 0.41874516],
        [0.6600683 , 0.98267126, 0.5768671 ],
        [0.02769125, 0.86124265, 0.10869396]],

       [[0.53754175, 0.2644632 , 0.9266491 ],
        [0.44722903, 0.4856404 , 0.39699185],
        [0.13047922, 0.68188083, 0.6198789 ],
        ...,
        [0.10199976, 0.0537411 , 0.9732318 ],
        [0.9919214 , 0.55092776, 0.82230055],
        [0.5163865 , 0.60801613, 0.34384835]],

       [[0.18016565, 0.21239138, 0.38615453],
        [0.28775942, 0.9006624 , 0.9089396 ],
        [0.7921039 , 0.58352494, 0.16005635],
        ...,
        [0.659994  , 0.02689016, 0.01844478],
        [0.9994308 , 0.11815572, 0.62885225],
        [0.07544076, 0.68293   , 0.5967432 ]],

       ...,

       [[0.41650033, 0.905632  , 0.85714865],
        [0.19

## 7. Find the min and max values of the tensor you created in 6.

In [ ]:
tensor_rmin = tf.reduce_min(tensor_r3)
tensor_rmax = tf.reduce_max(tensor_r3)
tensor_rmin, tensor_rmax

(<tf.Tensor: shape=(), dtype=float32, numpy=3.5762787e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99999166>)

## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
tf.random.set_seed(10)
tensor_rs3 = tf.random.uniform(shape=[1, 224, 224,3], minval=0, maxval=1,seed=10)
tensor_rs3

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.9574727 , 0.8584739 , 0.6193379 ],
         [0.2191757 , 0.31577528, 0.7001637 ],
         [0.1357553 , 0.90233886, 0.57843506],
         ...,
         [0.6916183 , 0.18287396, 0.41874516],
         [0.6600683 , 0.98267126, 0.5768671 ],
         [0.02769125, 0.86124265, 0.10869396]],

        [[0.53754175, 0.2644632 , 0.9266491 ],
         [0.44722903, 0.4856404 , 0.39699185],
         [0.13047922, 0.68188083, 0.6198789 ],
         ...,
         [0.10199976, 0.0537411 , 0.9732318 ],
         [0.9919214 , 0.55092776, 0.82230055],
         [0.5163865 , 0.60801613, 0.34384835]],

        [[0.18016565, 0.21239138, 0.38615453],
         [0.28775942, 0.9006624 , 0.9089396 ],
         [0.7921039 , 0.58352494, 0.16005635],
         ...,
         [0.659994  , 0.02689016, 0.01844478],
         [0.9994308 , 0.11815572, 0.62885225],
         [0.07544076, 0.68293   , 0.5967432 ]],

        ...,

        [[0.41650033, 0.905632  , 

In [ ]:
tensor_rs3.shape

TensorShape([1, 224, 224, 3])

In [ ]:
tensor_rs3_squeezed = tf.squeeze(tensor_rs3)
tensor_rs3_squeezed, tensor_rs3_squeezed.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.9574727 , 0.8584739 , 0.6193379 ],
         [0.2191757 , 0.31577528, 0.7001637 ],
         [0.1357553 , 0.90233886, 0.57843506],
         ...,
         [0.6916183 , 0.18287396, 0.41874516],
         [0.6600683 , 0.98267126, 0.5768671 ],
         [0.02769125, 0.86124265, 0.10869396]],
 
        [[0.53754175, 0.2644632 , 0.9266491 ],
         [0.44722903, 0.4856404 , 0.39699185],
         [0.13047922, 0.68188083, 0.6198789 ],
         ...,
         [0.10199976, 0.0537411 , 0.9732318 ],
         [0.9919214 , 0.55092776, 0.82230055],
         [0.5163865 , 0.60801613, 0.34384835]],
 
        [[0.18016565, 0.21239138, 0.38615453],
         [0.28775942, 0.9006624 , 0.9089396 ],
         [0.7921039 , 0.58352494, 0.16005635],
         ...,
         [0.659994  , 0.02689016, 0.01844478],
         [0.9994308 , 0.11815572, 0.62885225],
         [0.07544076, 0.68293   , 0.5967432 ]],
 
        ...,
 
        [[0.41650033, 0.905632  

## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [ ]:
tf.random.set_seed(12)
tensor_r4 = tf.random.uniform(shape=[10], seed=12)
tensor_r4

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.27525985, 0.33474183, 0.64594996, 0.92090166, 0.4241612 ,
       0.26951516, 0.38188124, 0.542416  , 0.9017867 , 0.59953225],
      dtype=float32)>

In [ ]:
tensor_r4_ind_min = tf.argmin(tensor_r4)
tensor_r4_ind_max = tf.argmax(tensor_r4)
tensor_r4_ind_min, tensor_r4_ind_max

## 10. One-hot encode the tensor you created in 9.

In [ ]:
tensor_r4_onehot = tf.one_hot(tf.cast(tensor_r4, dtype=tf.int32), depth=10)
tensor_r4_onehot

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

Thanks a lot for coming upto the end.

***KEEP LEARNING***
