<a href="https://colab.research.google.com/github/kunalburgul/MLDS_Learning/blob/master/Pytorch/jovian/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('01-tensor-operations')
jovian.set_colab_id('1DZ3okZvnl3YITWeROTIPfQ7dP6bv33RV')

# Basic Pytorch functions

An short introduction about PyTorch and about the chosen functions. 

- numel
- randint
- from_numpy
- reshape
- cat


Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## numel - torch.numel()

This function helps us finding the out the total number of elements in the input tensor.

In [ ]:
# Example 1  - Generating a random tensor and calculating the noumner of elements present in the tensor
t1 = torch.randn(1, 2)
print(t1)
torch.numel(t1)

tensor([[-0.2203, -1.0077]])


2

As similar to the len() funciton in the normal python we can use the numel() funciton in pytorch to calculate the number of tensors present.

Here in the above example there are have give a example of t dimensinal tensor

In [ ]:
# Example 2 - working
t2 = torch.zeros(3, 3)
print(t2)
torch.numel(t2)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


9

Here in the above example we can see that we can calculate a number of elements in the tensor matrix created through the torch.zeros funciton similar to that.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.numel([1])

TypeError: ignored

Only tensors are given as input to the numel() function if we try to pass array, vector or any other value we may get the following error.

This fuction is very useful when we are calculating the average values.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kunal-burgul/01-tensor-operations


'https://jovian.ai/kunal-burgul/01-tensor-operations'

## randint - torch.randint()

Randint is a function used to create a tensor filled with random integers generated uniformly between lower and upper limit.

In [ ]:
# Example 1 - generating random tensor
torch.randint(3, 5, (3,))

tensor([4, 4, 4])

We need to pass the 3 parameter for the randint function that are lower limit, upper limit and the size of the tensor we need to define.

In [ ]:
# Example 2 - generating random rensor without specifying the 'low' parameter
torch.randint(10, (2, 2))

tensor([[1, 5],
        [6, 3]])

If we do not specify the lower limit to the randint function then default value 0 is assigned to the lower limit

In [ ]:
# Example 3 - incorrect call
torch.randint(10, (2))

TypeError: ignored

The size parameter of the function must be a valid Tuple. In case one dimension tensor needs to be created, the following syntax can be used (2,).

randint is a very useful function to create a tensor with dummy values for experimentation purpose.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kunal-burgul/01-tensor-operations


'https://jovian.ai/kunal-burgul/01-tensor-operations'

## from_numpy - torch.from_numpy()

This function is used to create a tensor form the numpy array.

In [ ]:
# Example 1 - Converting the numpy array into the tensor
import numpy as np
a = np.array([1, 2, 3])
t = torch.from_numpy(a)
t

tensor([1, 2, 3])

We have the create a numpy array using the np.array() function. Then we have converted the numpy to tensor uisng the from_numpy function.

In [ ]:
# Example 2 - Accessing the tensor values through the index and replacing them 
t[0] = -1
t

tensor([-1,  2,  3])

We can replace the value of the tensor by going through the index positions of he tensor.

In [ ]:
# Example 3 - We cannot pass a multi-data array to create a tensor
c = np.array([1,2.,'c'])
print(c)
torch.from_numpy(c)

['1' '2.0' 'c']


TypeError: ignored

When we included a string in the numpy array and tried to convert it to torch tensors, we got an error. So, when converting the numpy array to tensors we need to nake sure that the data type of elements in the numpy array is integer, float or boolean.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kunal-burgul/01-tensor-operations


'https://jovian.ai/kunal-burgul/01-tensor-operations'

## reshape - torch.reshape()

Returns a tensor with the same data and number of elements as input, but with the specified shape. 

In [ ]:
# Example 1 - Using the reshape function to convert the vector into a matrix
a = torch.arange(4.)
print(a)
torch.reshape(a, (2, 2))

tensor([0., 1., 2., 3.])


tensor([[0., 1.],
        [2., 3.]])

In the above example we have created a vector using the arange function and then converted it into a matrix using a torch.reshape function.

In [ ]:
# Example 2 - Using the reshape function to convert the matrix to vector 
b = torch.tensor([[0, 1], [2, 3]])
t1 = torch.reshape(b, (-1,))

As similar to the previous example we can use the reshape function in a reverse from to convert matrix to a vector format.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.reshape(t1,(2,7))

RuntimeError: ignored

Though we can reshape tensors using torch.reshape(), we must be careful when declaring the size. In the example above, the tensor having size 2x2 can be reshaped into either 1x4 or 4x1 from the original shape. Therefore, we cannot declare some arbitrary shape for the resulting tensor such as 2x7.

`torch.reshape()` helps us transform tensors into the desired shape for any calculations. However, care must be taken when declaring the desired shape for the resulting tensor.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kunal-burgul/01-tensor-operations


'https://jovian.ai/kunal-burgul/01-tensor-operations'

## car - torch.cat()

Concatenates the given sequence of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [ ]:
# Example 1 - merging tensors vertically
x = torch.randn(2, 3)
x
torch.cat((x, x, x), 0)

tensor([[-1.1793,  0.5625,  1.3894],
        [-1.7932, -0.0560,  1.4345],
        [-1.1793,  0.5625,  1.3894],
        [-1.7932, -0.0560,  1.4345],
        [-1.1793,  0.5625,  1.3894],
        [-1.7932, -0.0560,  1.4345]])

In the above example we pass the value 0 as dimension of the so merge vertically

In [ ]:
# Example 2 - merging tensors horizontally
torch.cat((x, x, x), 1)

tensor([[-1.1793,  0.5625,  1.3894, -1.1793,  0.5625,  1.3894, -1.1793,  0.5625,
          1.3894],
        [-1.7932, -0.0560,  1.4345, -1.7932, -0.0560,  1.4345, -1.7932, -0.0560,
          1.4345]])

Similar to the previous example the dimension value 1 is used for merging horizontally.

In [ ]:
# Example 3 - 
torch.cat(([1, 2, 3], x), 1)

TypeError: ignored

Merging only happens between and list-of-tensors --> list-of-tensors and not betweem normal-values --> list-of-tensors vice-versa.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kunal-burgul/01-tensor-operations


'https://jovian.ai/kunal-burgul/01-tensor-operations'

## Conclusion

The notebook can be summarised as follows -

|Name|Returns|Parameters|Caution|
|:---:|:---:|:---:|:---:|
|torch.numel()|number of elements present in the tensor| comlplete tensor value need to be passed|only tensors should be passed|
|torch.randint()|tensor with a random number of int elements|size of input with lower and upper limit|proper tuple value should be passed if lower limit is not mentioned|
|torch.from_numpy()|tensor containing elements form the numpy array|input a normal or a numpy array|multi-data array can't be passed|
|torch.reshape()|Tensor with desired shape|Input Tensor and Desired shape|Clear definition of shape|
|torch.cat()|Concatenated tensor based on user defined sequence|dim-Dimension for concatenation|list-of-tensors and a single tensor dosen't merges|

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* PyTorch Wikipedia : https://en.wikipedia.org/wiki/PyTorch

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kunal-burgul/01-tensor-operations


'https://jovian.ai/kunal-burgul/01-tensor-operations'